/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db;


import fi.jubic.quanta.db.tables.Anomaly;
import fi.jubic.quanta.db.tables.Column;
import fi.jubic.quanta.db.tables.DataConnection;
import fi.jubic.quanta.db.tables.DataSeries;
import fi.jubic.quanta.db.tables.ExternalClient;
import fi.jubic.quanta.db.tables.Invocation;
import fi.jubic.quanta.db.tables.InvocationColumnSelector;
import fi.jubic.quanta.db.tables.InvocationOutputColumn;
import fi.jubic.quanta.db.tables.InvocationParameter;
import fi.jubic.quanta.db.tables.SeriesResult;
import fi.jubic.quanta.db.tables.SeriesTable;
import fi.jubic.quanta.db.tables.Tag;
import fi.jubic.quanta.db.tables.TagDataconnection;
import fi.jubic.quanta.db.tables.TagTask;
import fi.jubic.quanta.db.tables.Task;
import fi.jubic.quanta.db.tables.TaskColumnSelector;
import fi.jubic.quanta.db.tables.TaskOutputColumn;
import fi.jubic.quanta.db.tables.TaskParameter;
import fi.jubic.quanta.db.tables.User;
import fi.jubic.quanta.db.tables.Worker;
import fi.jubic.quanta.db.tables.WorkerDefinition;
import fi.jubic.quanta.db.tables.WorkerDefinitionColumn;
import fi.jubic.quanta.db.tables.WorkerParameter;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>anomaly</code>.
     */
    public final Anomaly ANOMALY = Anomaly.ANOMALY;

    /**
     * The table <code>column</code>.
     */
    public final Column COLUMN = Column.COLUMN;

    /**
     * The table <code>data_connection</code>.
     */
    public final DataConnection DATA_CONNECTION = DataConnection.DATA_CONNECTION;

    /**
     * The table <code>data_series</code>.
     */
    public final DataSeries DATA_SERIES = DataSeries.DATA_SERIES;

    /**
     * The table <code>external_client</code>.
     */
    public final ExternalClient EXTERNAL_CLIENT = ExternalClient.EXTERNAL_CLIENT;

    /**
     * The table <code>invocation</code>.
     */
    public final Invocation INVOCATION = Invocation.INVOCATION;

    /**
     * The table <code>invocation_column_selector</code>.
     */
    public final InvocationColumnSelector INVOCATION_COLUMN_SELECTOR = InvocationColumnSelector.INVOCATION_COLUMN_SELECTOR;

    /**
     * The table <code>invocation_output_column</code>.
     */
    public final InvocationOutputColumn INVOCATION_OUTPUT_COLUMN = InvocationOutputColumn.INVOCATION_OUTPUT_COLUMN;

    /**
     * The table <code>invocation_parameter</code>.
     */
    public final InvocationParameter INVOCATION_PARAMETER = InvocationParameter.INVOCATION_PARAMETER;

    /**
     * The table <code>series_result</code>.
     */
    public final SeriesResult SERIES_RESULT = SeriesResult.SERIES_RESULT;

    /**
     * The table <code>series_table</code>.
     */
    public final SeriesTable SERIES_TABLE = SeriesTable.SERIES_TABLE;

    /**
     * The table <code>tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>tag_dataconnection</code>.
     */
    public final TagDataconnection TAG_DATACONNECTION = TagDataconnection.TAG_DATACONNECTION;

    /**
     * The table <code>tag_task</code>.
     */
    public final TagTask TAG_TASK = TagTask.TAG_TASK;

    /**
     * The table <code>task</code>.
     */
    public final Task TASK = Task.TASK;

    /**
     * The table <code>task_column_selector</code>.
     */
    public final TaskColumnSelector TASK_COLUMN_SELECTOR = TaskColumnSelector.TASK_COLUMN_SELECTOR;

    /**
     * The table <code>task_output_column</code>.
     */
    public final TaskOutputColumn TASK_OUTPUT_COLUMN = TaskOutputColumn.TASK_OUTPUT_COLUMN;

    /**
     * The table <code>task_parameter</code>.
     */
    public final TaskParameter TASK_PARAMETER = TaskParameter.TASK_PARAMETER;

    /**
     * The table <code>user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>worker</code>.
     */
    public final Worker WORKER = Worker.WORKER;

    /**
     * The table <code>worker_definition</code>.
     */
    public final WorkerDefinition WORKER_DEFINITION = WorkerDefinition.WORKER_DEFINITION;

    /**
     * The table <code>worker_definition_column</code>.
     */
    public final WorkerDefinitionColumn WORKER_DEFINITION_COLUMN = WorkerDefinitionColumn.WORKER_DEFINITION_COLUMN;

    /**
     * The table <code>worker_parameter</code>.
     */
    public final WorkerParameter WORKER_PARAMETER = WorkerParameter.WORKER_PARAMETER;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Anomaly.ANOMALY,
            Column.COLUMN,
            DataConnection.DATA_CONNECTION,
            DataSeries.DATA_SERIES,
            ExternalClient.EXTERNAL_CLIENT,
            Invocation.INVOCATION,
            InvocationColumnSelector.INVOCATION_COLUMN_SELECTOR,
            InvocationOutputColumn.INVOCATION_OUTPUT_COLUMN,
            InvocationParameter.INVOCATION_PARAMETER,
            SeriesResult.SERIES_RESULT,
            SeriesTable.SERIES_TABLE,
            Tag.TAG,
            TagDataconnection.TAG_DATACONNECTION,
            TagTask.TAG_TASK,
            Task.TASK,
            TaskColumnSelector.TASK_COLUMN_SELECTOR,
            TaskOutputColumn.TASK_OUTPUT_COLUMN,
            TaskParameter.TASK_PARAMETER,
            User.USER,
            Worker.WORKER,
            WorkerDefinition.WORKER_DEFINITION,
            WorkerDefinitionColumn.WORKER_DEFINITION_COLUMN,
            WorkerParameter.WORKER_PARAMETER);
    }
}
