/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db;


import fi.jubic.quanta.db.tables.Column;
import fi.jubic.quanta.db.tables.DataConnection;
import fi.jubic.quanta.db.tables.DataSeries;
import fi.jubic.quanta.db.tables.DetectionResult;
import fi.jubic.quanta.db.tables.ExternalClient;
import fi.jubic.quanta.db.tables.Invocation;
import fi.jubic.quanta.db.tables.InvocationColumnSelector;
import fi.jubic.quanta.db.tables.InvocationOutputColumn;
import fi.jubic.quanta.db.tables.SeriesResult;
import fi.jubic.quanta.db.tables.SeriesTable;
import fi.jubic.quanta.db.tables.Task;
import fi.jubic.quanta.db.tables.TaskColumnSelector;
import fi.jubic.quanta.db.tables.TaskOutputColumn;
import fi.jubic.quanta.db.tables.User;
import fi.jubic.quanta.db.tables.Worker;
import fi.jubic.quanta.db.tables.WorkerDefinition;
import fi.jubic.quanta.db.tables.WorkerDefinitionColumn;
import fi.jubic.quanta.db.tables.WorkerParameter;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>column</code>.
     */
    public static final Column COLUMN = fi.jubic.quanta.db.tables.Column.COLUMN;

    /**
     * The table <code>data_connection</code>.
     */
    public static final DataConnection DATA_CONNECTION = fi.jubic.quanta.db.tables.DataConnection.DATA_CONNECTION;

    /**
     * The table <code>data_series</code>.
     */
    public static final DataSeries DATA_SERIES = fi.jubic.quanta.db.tables.DataSeries.DATA_SERIES;

    /**
     * The table <code>detection_result</code>.
     */
    public static final DetectionResult DETECTION_RESULT = fi.jubic.quanta.db.tables.DetectionResult.DETECTION_RESULT;

    /**
     * The table <code>external_client</code>.
     */
    public static final ExternalClient EXTERNAL_CLIENT = fi.jubic.quanta.db.tables.ExternalClient.EXTERNAL_CLIENT;

    /**
     * The table <code>invocation</code>.
     */
    public static final Invocation INVOCATION = fi.jubic.quanta.db.tables.Invocation.INVOCATION;

    /**
     * The table <code>invocation_column_selector</code>.
     */
    public static final InvocationColumnSelector INVOCATION_COLUMN_SELECTOR = fi.jubic.quanta.db.tables.InvocationColumnSelector.INVOCATION_COLUMN_SELECTOR;

    /**
     * The table <code>invocation_output_column</code>.
     */
    public static final InvocationOutputColumn INVOCATION_OUTPUT_COLUMN = fi.jubic.quanta.db.tables.InvocationOutputColumn.INVOCATION_OUTPUT_COLUMN;

    /**
     * The table <code>series_result</code>.
     */
    public static final SeriesResult SERIES_RESULT = fi.jubic.quanta.db.tables.SeriesResult.SERIES_RESULT;

    /**
     * The table <code>series_table</code>.
     */
    public static final SeriesTable SERIES_TABLE = fi.jubic.quanta.db.tables.SeriesTable.SERIES_TABLE;

    /**
     * The table <code>task</code>.
     */
    public static final Task TASK = fi.jubic.quanta.db.tables.Task.TASK;

    /**
     * The table <code>task_column_selector</code>.
     */
    public static final TaskColumnSelector TASK_COLUMN_SELECTOR = fi.jubic.quanta.db.tables.TaskColumnSelector.TASK_COLUMN_SELECTOR;

    /**
     * The table <code>task_output_column</code>.
     */
    public static final TaskOutputColumn TASK_OUTPUT_COLUMN = fi.jubic.quanta.db.tables.TaskOutputColumn.TASK_OUTPUT_COLUMN;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = fi.jubic.quanta.db.tables.User.USER;

    /**
     * The table <code>worker</code>.
     */
    public static final Worker WORKER = fi.jubic.quanta.db.tables.Worker.WORKER;

    /**
     * The table <code>worker_definition</code>.
     */
    public static final WorkerDefinition WORKER_DEFINITION = fi.jubic.quanta.db.tables.WorkerDefinition.WORKER_DEFINITION;

    /**
     * The table <code>worker_definition_column</code>.
     */
    public static final WorkerDefinitionColumn WORKER_DEFINITION_COLUMN = fi.jubic.quanta.db.tables.WorkerDefinitionColumn.WORKER_DEFINITION_COLUMN;

    /**
     * The table <code>worker_parameter</code>.
     */
    public static final WorkerParameter WORKER_PARAMETER = fi.jubic.quanta.db.tables.WorkerParameter.WORKER_PARAMETER;
}
