/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db;


import fi.jubic.quanta.db.tables.Anomaly;
import fi.jubic.quanta.db.tables.Column;
import fi.jubic.quanta.db.tables.DataConnection;
import fi.jubic.quanta.db.tables.DataSeries;
import fi.jubic.quanta.db.tables.ExternalClient;
import fi.jubic.quanta.db.tables.Invocation;
import fi.jubic.quanta.db.tables.InvocationColumnSelector;
import fi.jubic.quanta.db.tables.InvocationOutputColumn;
import fi.jubic.quanta.db.tables.InvocationParameter;
import fi.jubic.quanta.db.tables.SeriesResult;
import fi.jubic.quanta.db.tables.SeriesTable;
import fi.jubic.quanta.db.tables.Tag;
import fi.jubic.quanta.db.tables.TagDataconnection;
import fi.jubic.quanta.db.tables.TagTask;
import fi.jubic.quanta.db.tables.Task;
import fi.jubic.quanta.db.tables.TaskColumnSelector;
import fi.jubic.quanta.db.tables.TaskOutputColumn;
import fi.jubic.quanta.db.tables.TaskParameter;
import fi.jubic.quanta.db.tables.User;
import fi.jubic.quanta.db.tables.Worker;
import fi.jubic.quanta.db.tables.WorkerDefinition;
import fi.jubic.quanta.db.tables.WorkerDefinitionColumn;
import fi.jubic.quanta.db.tables.WorkerParameter;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>anomaly</code>.
     */
    public static final Anomaly ANOMALY = Anomaly.ANOMALY;

    /**
     * The table <code>column</code>.
     */
    public static final Column COLUMN = Column.COLUMN;

    /**
     * The table <code>data_connection</code>.
     */
    public static final DataConnection DATA_CONNECTION = DataConnection.DATA_CONNECTION;

    /**
     * The table <code>data_series</code>.
     */
    public static final DataSeries DATA_SERIES = DataSeries.DATA_SERIES;

    /**
     * The table <code>external_client</code>.
     */
    public static final ExternalClient EXTERNAL_CLIENT = ExternalClient.EXTERNAL_CLIENT;

    /**
     * The table <code>invocation</code>.
     */
    public static final Invocation INVOCATION = Invocation.INVOCATION;

    /**
     * The table <code>invocation_column_selector</code>.
     */
    public static final InvocationColumnSelector INVOCATION_COLUMN_SELECTOR = InvocationColumnSelector.INVOCATION_COLUMN_SELECTOR;

    /**
     * The table <code>invocation_output_column</code>.
     */
    public static final InvocationOutputColumn INVOCATION_OUTPUT_COLUMN = InvocationOutputColumn.INVOCATION_OUTPUT_COLUMN;

    /**
     * The table <code>invocation_parameter</code>.
     */
    public static final InvocationParameter INVOCATION_PARAMETER = InvocationParameter.INVOCATION_PARAMETER;

    /**
     * The table <code>series_result</code>.
     */
    public static final SeriesResult SERIES_RESULT = SeriesResult.SERIES_RESULT;

    /**
     * The table <code>series_table</code>.
     */
    public static final SeriesTable SERIES_TABLE = SeriesTable.SERIES_TABLE;

    /**
     * The table <code>tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>tag_dataconnection</code>.
     */
    public static final TagDataconnection TAG_DATACONNECTION = TagDataconnection.TAG_DATACONNECTION;

    /**
     * The table <code>tag_task</code>.
     */
    public static final TagTask TAG_TASK = TagTask.TAG_TASK;

    /**
     * The table <code>task</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>task_column_selector</code>.
     */
    public static final TaskColumnSelector TASK_COLUMN_SELECTOR = TaskColumnSelector.TASK_COLUMN_SELECTOR;

    /**
     * The table <code>task_output_column</code>.
     */
    public static final TaskOutputColumn TASK_OUTPUT_COLUMN = TaskOutputColumn.TASK_OUTPUT_COLUMN;

    /**
     * The table <code>task_parameter</code>.
     */
    public static final TaskParameter TASK_PARAMETER = TaskParameter.TASK_PARAMETER;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>worker</code>.
     */
    public static final Worker WORKER = Worker.WORKER;

    /**
     * The table <code>worker_definition</code>.
     */
    public static final WorkerDefinition WORKER_DEFINITION = WorkerDefinition.WORKER_DEFINITION;

    /**
     * The table <code>worker_definition_column</code>.
     */
    public static final WorkerDefinitionColumn WORKER_DEFINITION_COLUMN = WorkerDefinitionColumn.WORKER_DEFINITION_COLUMN;

    /**
     * The table <code>worker_parameter</code>.
     */
    public static final WorkerParameter WORKER_PARAMETER = WorkerParameter.WORKER_PARAMETER;
}
