/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.ColumnRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Column extends TableImpl<ColumnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>column</code>
     */
    public static final Column COLUMN = new Column();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ColumnRecord> getRecordType() {
        return ColumnRecord.class;
    }

    /**
     * The column <code>column.id</code>.
     */
    public final TableField<ColumnRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>column.name</code>.
     */
    public final TableField<ColumnRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>column.class</code>.
     */
    public final TableField<ColumnRecord, String> CLASS = createField(DSL.name("class"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>column.format</code>.
     */
    public final TableField<ColumnRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>column.nullable</code>.
     */
    public final TableField<ColumnRecord, Boolean> NULLABLE = createField(DSL.name("nullable"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>column.data_series_id</code>.
     */
    public final TableField<ColumnRecord, Long> DATA_SERIES_ID = createField(DSL.name("data_series_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>column.index</code>.
     */
    public final TableField<ColumnRecord, Integer> INDEX = createField(DSL.name("index"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    private Column(Name alias, Table<ColumnRecord> aliased) {
        this(alias, aliased, null);
    }

    private Column(Name alias, Table<ColumnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>column</code> table reference
     */
    public Column(String alias) {
        this(DSL.name(alias), COLUMN);
    }

    /**
     * Create an aliased <code>column</code> table reference
     */
    public Column(Name alias) {
        this(alias, COLUMN);
    }

    /**
     * Create a <code>column</code> table reference
     */
    public Column() {
        this(DSL.name("column"), null);
    }

    public <O extends Record> Column(Table<O> child, ForeignKey<O, ColumnRecord> key) {
        super(child, key, COLUMN);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ColumnRecord, Long> getIdentity() {
        return (Identity<ColumnRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ColumnRecord> getPrimaryKey() {
        return Keys.COLUMN_PKEY;
    }

    @Override
    public List<UniqueKey<ColumnRecord>> getKeys() {
        return Arrays.<UniqueKey<ColumnRecord>>asList(Keys.COLUMN_PKEY);
    }

    @Override
    public List<ForeignKey<ColumnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ColumnRecord, ?>>asList(Keys.COLUMN__FK_COLUMN_DATA_SERIES_ID);
    }

    public DataSeries dataSeries() {
        return new DataSeries(this, Keys.COLUMN__FK_COLUMN_DATA_SERIES_ID);
    }

    @Override
    public Column as(String alias) {
        return new Column(DSL.name(alias), this);
    }

    @Override
    public Column as(Name alias) {
        return new Column(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Column rename(String name) {
        return new Column(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Column rename(Name name) {
        return new Column(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, String, Boolean, Long, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
