/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Indexes;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.DataConnectionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataConnection extends TableImpl<DataConnectionRecord> {

    private static final long serialVersionUID = 894835827;

    /**
     * The reference instance of <code>data_connection</code>
     */
    public static final DataConnection DATA_CONNECTION = new DataConnection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataConnectionRecord> getRecordType() {
        return DataConnectionRecord.class;
    }

    /**
     * The column <code>data_connection.id</code>.
     */
    public final TableField<DataConnectionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>data_connection.name</code>.
     */
    public final TableField<DataConnectionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>data_connection.description</code>.
     */
    public final TableField<DataConnectionRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>data_connection.type</code>.
     */
    public final TableField<DataConnectionRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>data_connection.configuration</code>.
     */
    public final TableField<DataConnectionRecord, String> CONFIGURATION = createField("configuration", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>data_connection.deleted_at</code>.
     */
    public final TableField<DataConnectionRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>data_connection</code> table reference
     */
    public DataConnection() {
        this(DSL.name("data_connection"), null);
    }

    /**
     * Create an aliased <code>data_connection</code> table reference
     */
    public DataConnection(String alias) {
        this(DSL.name(alias), DATA_CONNECTION);
    }

    /**
     * Create an aliased <code>data_connection</code> table reference
     */
    public DataConnection(Name alias) {
        this(alias, DATA_CONNECTION);
    }

    private DataConnection(Name alias, Table<DataConnectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private DataConnection(Name alias, Table<DataConnectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DataConnection(Table<O> child, ForeignKey<O, DataConnectionRecord> key) {
        super(child, key, DATA_CONNECTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DATA_CONNECTION_NAME_KEY, Indexes.DATA_CONNECTION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DataConnectionRecord> getPrimaryKey() {
        return Keys.DATA_CONNECTION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DataConnectionRecord>> getKeys() {
        return Arrays.<UniqueKey<DataConnectionRecord>>asList(Keys.DATA_CONNECTION_PKEY, Keys.DATA_CONNECTION_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataConnection as(String alias) {
        return new DataConnection(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataConnection as(Name alias) {
        return new DataConnection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataConnection rename(String name) {
        return new DataConnection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataConnection rename(Name name) {
        return new DataConnection(name, null);
    }
}
