/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.InvocationParameterRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvocationParameter extends TableImpl<InvocationParameterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>invocation_parameter</code>
     */
    public static final InvocationParameter INVOCATION_PARAMETER = new InvocationParameter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvocationParameterRecord> getRecordType() {
        return InvocationParameterRecord.class;
    }

    /**
     * The column <code>invocation_parameter.id</code>.
     */
    public final TableField<InvocationParameterRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>invocation_parameter.name</code>.
     */
    public final TableField<InvocationParameterRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>invocation_parameter.value</code>.
     */
    public final TableField<InvocationParameterRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>invocation_parameter.invocation_id</code>.
     */
    public final TableField<InvocationParameterRecord, Long> INVOCATION_ID = createField(DSL.name("invocation_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private InvocationParameter(Name alias, Table<InvocationParameterRecord> aliased) {
        this(alias, aliased, null);
    }

    private InvocationParameter(Name alias, Table<InvocationParameterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>invocation_parameter</code> table reference
     */
    public InvocationParameter(String alias) {
        this(DSL.name(alias), INVOCATION_PARAMETER);
    }

    /**
     * Create an aliased <code>invocation_parameter</code> table reference
     */
    public InvocationParameter(Name alias) {
        this(alias, INVOCATION_PARAMETER);
    }

    /**
     * Create a <code>invocation_parameter</code> table reference
     */
    public InvocationParameter() {
        this(DSL.name("invocation_parameter"), null);
    }

    public <O extends Record> InvocationParameter(Table<O> child, ForeignKey<O, InvocationParameterRecord> key) {
        super(child, key, INVOCATION_PARAMETER);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<InvocationParameterRecord, Long> getIdentity() {
        return (Identity<InvocationParameterRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InvocationParameterRecord> getPrimaryKey() {
        return Keys.INVOCATION_PARAMETER_PKEY;
    }

    @Override
    public List<UniqueKey<InvocationParameterRecord>> getKeys() {
        return Arrays.<UniqueKey<InvocationParameterRecord>>asList(Keys.INVOCATION_PARAMETER_PKEY);
    }

    @Override
    public List<ForeignKey<InvocationParameterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvocationParameterRecord, ?>>asList(Keys.INVOCATION_PARAMETER__FK_INVOCATION_PARAMETER);
    }

    public Invocation invocation() {
        return new Invocation(this, Keys.INVOCATION_PARAMETER__FK_INVOCATION_PARAMETER);
    }

    @Override
    public InvocationParameter as(String alias) {
        return new InvocationParameter(DSL.name(alias), this);
    }

    @Override
    public InvocationParameter as(Name alias) {
        return new InvocationParameter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InvocationParameter rename(String name) {
        return new InvocationParameter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvocationParameter rename(Name name) {
        return new InvocationParameter(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
