/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.InvocationColumnSelectorRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvocationColumnSelector extends TableImpl<InvocationColumnSelectorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>invocation_column_selector</code>
     */
    public static final InvocationColumnSelector INVOCATION_COLUMN_SELECTOR = new InvocationColumnSelector();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvocationColumnSelectorRecord> getRecordType() {
        return InvocationColumnSelectorRecord.class;
    }

    /**
     * The column <code>invocation_column_selector.id</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>invocation_column_selector.column_index</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Integer> COLUMN_INDEX = createField(DSL.name("column_index"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>invocation_column_selector.column_name</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, String> COLUMN_NAME = createField(DSL.name("column_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>invocation_column_selector.class</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, String> CLASS = createField(DSL.name("class"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>invocation_column_selector.format</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>invocation_column_selector.nullable</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Boolean> NULLABLE = createField(DSL.name("nullable"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>invocation_column_selector.modifier</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, String> MODIFIER = createField(DSL.name("modifier"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>invocation_column_selector.alias</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, String> ALIAS = createField(DSL.name("alias"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>invocation_column_selector.data_series_id</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Long> DATA_SERIES_ID = createField(DSL.name("data_series_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>invocation_column_selector.invocation_id</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Long> INVOCATION_ID = createField(DSL.name("invocation_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>invocation_column_selector.worker_definition_column_id</code>.
     */
    public final TableField<InvocationColumnSelectorRecord, Long> WORKER_DEFINITION_COLUMN_ID = createField(DSL.name("worker_definition_column_id"), SQLDataType.BIGINT, this, "");

    private InvocationColumnSelector(Name alias, Table<InvocationColumnSelectorRecord> aliased) {
        this(alias, aliased, null);
    }

    private InvocationColumnSelector(Name alias, Table<InvocationColumnSelectorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>invocation_column_selector</code> table reference
     */
    public InvocationColumnSelector(String alias) {
        this(DSL.name(alias), INVOCATION_COLUMN_SELECTOR);
    }

    /**
     * Create an aliased <code>invocation_column_selector</code> table reference
     */
    public InvocationColumnSelector(Name alias) {
        this(alias, INVOCATION_COLUMN_SELECTOR);
    }

    /**
     * Create a <code>invocation_column_selector</code> table reference
     */
    public InvocationColumnSelector() {
        this(DSL.name("invocation_column_selector"), null);
    }

    public <O extends Record> InvocationColumnSelector(Table<O> child, ForeignKey<O, InvocationColumnSelectorRecord> key) {
        super(child, key, INVOCATION_COLUMN_SELECTOR);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<InvocationColumnSelectorRecord, Long> getIdentity() {
        return (Identity<InvocationColumnSelectorRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InvocationColumnSelectorRecord> getPrimaryKey() {
        return Keys.INVOCATION_COLUMN_SELECTOR_PKEY;
    }

    @Override
    public List<UniqueKey<InvocationColumnSelectorRecord>> getKeys() {
        return Arrays.<UniqueKey<InvocationColumnSelectorRecord>>asList(Keys.INVOCATION_COLUMN_SELECTOR_PKEY);
    }

    @Override
    public List<ForeignKey<InvocationColumnSelectorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvocationColumnSelectorRecord, ?>>asList(Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_DATA_SERIES_ID, Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_INVOCATION_ID, Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_WORKER_DEFINITION_COLUMN_ID);
    }

    public DataSeries dataSeries() {
        return new DataSeries(this, Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_DATA_SERIES_ID);
    }

    public Invocation invocation() {
        return new Invocation(this, Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_INVOCATION_ID);
    }

    public WorkerDefinitionColumn workerDefinitionColumn() {
        return new WorkerDefinitionColumn(this, Keys.INVOCATION_COLUMN_SELECTOR__FK_INVOCATION_COLUMN_SELECTOR_WORKER_DEFINITION_COLUMN_ID);
    }

    @Override
    public InvocationColumnSelector as(String alias) {
        return new InvocationColumnSelector(DSL.name(alias), this);
    }

    @Override
    public InvocationColumnSelector as(Name alias) {
        return new InvocationColumnSelector(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InvocationColumnSelector rename(String name) {
        return new InvocationColumnSelector(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InvocationColumnSelector rename(Name name) {
        return new InvocationColumnSelector(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Integer, String, String, String, Boolean, String, String, Long, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
