/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Indexes;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.InvocationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invocation extends TableImpl<InvocationRecord> {

    private static final long serialVersionUID = 316796121;

    /**
     * The reference instance of <code>invocation</code>
     */
    public static final Invocation INVOCATION = new Invocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvocationRecord> getRecordType() {
        return InvocationRecord.class;
    }

    /**
     * The column <code>invocation.id</code>.
     */
    public final TableField<InvocationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>invocation.invocation_number</code>.
     */
    public final TableField<InvocationRecord, Long> INVOCATION_NUMBER = createField("invocation_number", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>invocation.status</code>.
     */
    public final TableField<InvocationRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>invocation.task_id</code>.
     */
    public final TableField<InvocationRecord, Long> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>invocation.worker_id</code>.
     */
    public final TableField<InvocationRecord, Long> WORKER_ID = createField("worker_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>invocation.config</code>.
     */
    public final TableField<InvocationRecord, String> CONFIG = createField("config", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>invocation.starting_time</code>.
     */
    public final TableField<InvocationRecord, Timestamp> STARTING_TIME = createField("starting_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>invocation.ending_time</code>.
     */
    public final TableField<InvocationRecord, Timestamp> ENDING_TIME = createField("ending_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>invocation.deleted_at</code>.
     */
    public final TableField<InvocationRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>invocation.additional_params</code>.
     */
    public final TableField<InvocationRecord, String> ADDITIONAL_PARAMS = createField("additional_params", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>invocation</code> table reference
     */
    public Invocation() {
        this(DSL.name("invocation"), null);
    }

    /**
     * Create an aliased <code>invocation</code> table reference
     */
    public Invocation(String alias) {
        this(DSL.name(alias), INVOCATION);
    }

    /**
     * Create an aliased <code>invocation</code> table reference
     */
    public Invocation(Name alias) {
        this(alias, INVOCATION);
    }

    private Invocation(Name alias, Table<InvocationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Invocation(Name alias, Table<InvocationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Invocation(Table<O> child, ForeignKey<O, InvocationRecord> key) {
        super(child, key, INVOCATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INVOCATION_PKEY, Indexes.INVOCATION_TASK_ID_INVOCATION_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InvocationRecord> getPrimaryKey() {
        return Keys.INVOCATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InvocationRecord>> getKeys() {
        return Arrays.<UniqueKey<InvocationRecord>>asList(Keys.INVOCATION_PKEY, Keys.INVOCATION_TASK_ID_INVOCATION_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InvocationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvocationRecord, ?>>asList(Keys.INVOCATION__FK_INVOCATION_TASK_ID, Keys.INVOCATION__FK_INVOCATION_WORKER_ID);
    }

    public Task task() {
        return new Task(this, Keys.INVOCATION__FK_INVOCATION_TASK_ID);
    }

    public Worker worker() {
        return new Worker(this, Keys.INVOCATION__FK_INVOCATION_WORKER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Invocation as(String alias) {
        return new Invocation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Invocation as(Name alias) {
        return new Invocation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invocation rename(String name) {
        return new Invocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Invocation rename(Name name) {
        return new Invocation(name, null);
    }
}
