/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.SeriesTableRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeriesTable extends TableImpl<SeriesTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>series_table</code>
     */
    public static final SeriesTable SERIES_TABLE = new SeriesTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeriesTableRecord> getRecordType() {
        return SeriesTableRecord.class;
    }

    /**
     * The column <code>series_table.id</code>.
     */
    public final TableField<SeriesTableRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>series_table.table_name</code>.
     */
    public final TableField<SeriesTableRecord, String> TABLE_NAME = createField(DSL.name("table_name"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>series_table.data_series_id</code>.
     */
    public final TableField<SeriesTableRecord, Long> DATA_SERIES_ID = createField(DSL.name("data_series_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>series_table.delete_at</code>.
     */
    public final TableField<SeriesTableRecord, LocalDateTime> DELETE_AT = createField(DSL.name("delete_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private SeriesTable(Name alias, Table<SeriesTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeriesTable(Name alias, Table<SeriesTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>series_table</code> table reference
     */
    public SeriesTable(String alias) {
        this(DSL.name(alias), SERIES_TABLE);
    }

    /**
     * Create an aliased <code>series_table</code> table reference
     */
    public SeriesTable(Name alias) {
        this(alias, SERIES_TABLE);
    }

    /**
     * Create a <code>series_table</code> table reference
     */
    public SeriesTable() {
        this(DSL.name("series_table"), null);
    }

    public <O extends Record> SeriesTable(Table<O> child, ForeignKey<O, SeriesTableRecord> key) {
        super(child, key, SERIES_TABLE);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<SeriesTableRecord, Long> getIdentity() {
        return (Identity<SeriesTableRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SeriesTableRecord> getPrimaryKey() {
        return Keys.SERIES_TABLE_PKEY;
    }

    @Override
    public List<UniqueKey<SeriesTableRecord>> getKeys() {
        return Arrays.<UniqueKey<SeriesTableRecord>>asList(Keys.SERIES_TABLE_PKEY);
    }

    @Override
    public List<ForeignKey<SeriesTableRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SeriesTableRecord, ?>>asList(Keys.SERIES_TABLE__FK_SERIES_TABLE_DATA_SERIES_ID);
    }

    public DataSeries dataSeries() {
        return new DataSeries(this, Keys.SERIES_TABLE__FK_SERIES_TABLE_DATA_SERIES_ID);
    }

    @Override
    public SeriesTable as(String alias) {
        return new SeriesTable(DSL.name(alias), this);
    }

    @Override
    public SeriesTable as(Name alias) {
        return new SeriesTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeriesTable rename(String name) {
        return new SeriesTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SeriesTable rename(Name name) {
        return new SeriesTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Long, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
