/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.TagTaskRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTask extends TableImpl<TagTaskRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tag_task</code>
     */
    public static final TagTask TAG_TASK = new TagTask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagTaskRecord> getRecordType() {
        return TagTaskRecord.class;
    }

    /**
     * The column <code>tag_task.tag_id</code>.
     */
    public final TableField<TagTaskRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>tag_task.task_id</code>.
     */
    public final TableField<TagTaskRecord, Long> TASK_ID = createField(DSL.name("task_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private TagTask(Name alias, Table<TagTaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private TagTask(Name alias, Table<TagTaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tag_task</code> table reference
     */
    public TagTask(String alias) {
        this(DSL.name(alias), TAG_TASK);
    }

    /**
     * Create an aliased <code>tag_task</code> table reference
     */
    public TagTask(Name alias) {
        this(alias, TAG_TASK);
    }

    /**
     * Create a <code>tag_task</code> table reference
     */
    public TagTask() {
        this(DSL.name("tag_task"), null);
    }

    public <O extends Record> TagTask(Table<O> child, ForeignKey<O, TagTaskRecord> key) {
        super(child, key, TAG_TASK);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TagTaskRecord> getPrimaryKey() {
        return Keys.PK_TAG_TASK;
    }

    @Override
    public List<UniqueKey<TagTaskRecord>> getKeys() {
        return Arrays.<UniqueKey<TagTaskRecord>>asList(Keys.PK_TAG_TASK);
    }

    @Override
    public TagTask as(String alias) {
        return new TagTask(DSL.name(alias), this);
    }

    @Override
    public TagTask as(Name alias) {
        return new TagTask(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTask rename(String name) {
        return new TagTask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTask rename(Name name) {
        return new TagTask(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
