/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Indexes;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.TaskParameterRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskParameter extends TableImpl<TaskParameterRecord> {

    private static final long serialVersionUID = -1851495825;

    /**
     * The reference instance of <code>task_parameter</code>
     */
    public static final TaskParameter TASK_PARAMETER = new TaskParameter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskParameterRecord> getRecordType() {
        return TaskParameterRecord.class;
    }

    /**
     * The column <code>task_parameter.id</code>.
     */
    public final TableField<TaskParameterRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>task_parameter.name</code>.
     */
    public final TableField<TaskParameterRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>task_parameter.value</code>.
     */
    public final TableField<TaskParameterRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>task_parameter.task_id</code>.
     */
    public final TableField<TaskParameterRecord, Long> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>task_parameter</code> table reference
     */
    public TaskParameter() {
        this(DSL.name("task_parameter"), null);
    }

    /**
     * Create an aliased <code>task_parameter</code> table reference
     */
    public TaskParameter(String alias) {
        this(DSL.name(alias), TASK_PARAMETER);
    }

    /**
     * Create an aliased <code>task_parameter</code> table reference
     */
    public TaskParameter(Name alias) {
        this(alias, TASK_PARAMETER);
    }

    private TaskParameter(Name alias, Table<TaskParameterRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskParameter(Name alias, Table<TaskParameterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TaskParameter(Table<O> child, ForeignKey<O, TaskParameterRecord> key) {
        super(child, key, TASK_PARAMETER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TASK_PARAMETER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TaskParameterRecord> getPrimaryKey() {
        return Keys.TASK_PARAMETER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TaskParameterRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskParameterRecord>>asList(Keys.TASK_PARAMETER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TaskParameterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TaskParameterRecord, ?>>asList(Keys.TASK_PARAMETER__FK_TASK_PARAMETER_TASK_ID);
    }

    public Task task() {
        return new Task(this, Keys.TASK_PARAMETER__FK_TASK_PARAMETER_TASK_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskParameter as(String alias) {
        return new TaskParameter(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskParameter as(Name alias) {
        return new TaskParameter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskParameter rename(String name) {
        return new TaskParameter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaskParameter rename(Name name) {
        return new TaskParameter(name, null);
    }
}
