/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.WorkerDefinitionColumnRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerDefinitionColumn extends TableImpl<WorkerDefinitionColumnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>worker_definition_column</code>
     */
    public static final WorkerDefinitionColumn WORKER_DEFINITION_COLUMN = new WorkerDefinitionColumn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkerDefinitionColumnRecord> getRecordType() {
        return WorkerDefinitionColumnRecord.class;
    }

    /**
     * The column <code>worker_definition_column.id</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>worker_definition_column.name</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.class</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> CLASS = createField(DSL.name("class"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.format</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> FORMAT = createField(DSL.name("format"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>worker_definition_column.nullable</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Boolean> NULLABLE = createField(DSL.name("nullable"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>worker_definition_column.column_type</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> COLUMN_TYPE = createField(DSL.name("column_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.index</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Integer> INDEX = createField(DSL.name("index"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>worker_definition_column.description</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.definition_id</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Long> DEFINITION_ID = createField(DSL.name("definition_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private WorkerDefinitionColumn(Name alias, Table<WorkerDefinitionColumnRecord> aliased) {
        this(alias, aliased, null);
    }

    private WorkerDefinitionColumn(Name alias, Table<WorkerDefinitionColumnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn(String alias) {
        this(DSL.name(alias), WORKER_DEFINITION_COLUMN);
    }

    /**
     * Create an aliased <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn(Name alias) {
        this(alias, WORKER_DEFINITION_COLUMN);
    }

    /**
     * Create a <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn() {
        this(DSL.name("worker_definition_column"), null);
    }

    public <O extends Record> WorkerDefinitionColumn(Table<O> child, ForeignKey<O, WorkerDefinitionColumnRecord> key) {
        super(child, key, WORKER_DEFINITION_COLUMN);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<WorkerDefinitionColumnRecord, Long> getIdentity() {
        return (Identity<WorkerDefinitionColumnRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WorkerDefinitionColumnRecord> getPrimaryKey() {
        return Keys.WORKER_DEFINITION_COLUMN_PKEY;
    }

    @Override
    public List<UniqueKey<WorkerDefinitionColumnRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkerDefinitionColumnRecord>>asList(Keys.WORKER_DEFINITION_COLUMN_PKEY);
    }

    @Override
    public List<ForeignKey<WorkerDefinitionColumnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WorkerDefinitionColumnRecord, ?>>asList(Keys.WORKER_DEFINITION_COLUMN__FK_WORKER_DEFINITION_INPUT_COLUMN_WORKER_DEFINITION_ID);
    }

    public WorkerDefinition workerDefinition() {
        return new WorkerDefinition(this, Keys.WORKER_DEFINITION_COLUMN__FK_WORKER_DEFINITION_INPUT_COLUMN_WORKER_DEFINITION_ID);
    }

    @Override
    public WorkerDefinitionColumn as(String alias) {
        return new WorkerDefinitionColumn(DSL.name(alias), this);
    }

    @Override
    public WorkerDefinitionColumn as(Name alias) {
        return new WorkerDefinitionColumn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkerDefinitionColumn rename(String name) {
        return new WorkerDefinitionColumn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkerDefinitionColumn rename(Name name) {
        return new WorkerDefinitionColumn(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Boolean, String, Integer, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
