/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables;


import fi.jubic.quanta.db.DefaultSchema;
import fi.jubic.quanta.db.Indexes;
import fi.jubic.quanta.db.Keys;
import fi.jubic.quanta.db.tables.records.WorkerDefinitionColumnRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerDefinitionColumn extends TableImpl<WorkerDefinitionColumnRecord> {

    private static final long serialVersionUID = -1878880207;

    /**
     * The reference instance of <code>worker_definition_column</code>
     */
    public static final WorkerDefinitionColumn WORKER_DEFINITION_COLUMN = new WorkerDefinitionColumn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorkerDefinitionColumnRecord> getRecordType() {
        return WorkerDefinitionColumnRecord.class;
    }

    /**
     * The column <code>worker_definition_column.id</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.name</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.class</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> CLASS = createField("class", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.format</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> FORMAT = createField("format", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>worker_definition_column.nullable</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Boolean> NULLABLE = createField("nullable", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>worker_definition_column.column_type</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> COLUMN_TYPE = createField("column_type", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.index</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Integer> INDEX = createField("index", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>worker_definition_column.description</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>worker_definition_column.definition_id</code>.
     */
    public final TableField<WorkerDefinitionColumnRecord, Long> DEFINITION_ID = createField("definition_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn() {
        this(DSL.name("worker_definition_column"), null);
    }

    /**
     * Create an aliased <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn(String alias) {
        this(DSL.name(alias), WORKER_DEFINITION_COLUMN);
    }

    /**
     * Create an aliased <code>worker_definition_column</code> table reference
     */
    public WorkerDefinitionColumn(Name alias) {
        this(alias, WORKER_DEFINITION_COLUMN);
    }

    private WorkerDefinitionColumn(Name alias, Table<WorkerDefinitionColumnRecord> aliased) {
        this(alias, aliased, null);
    }

    private WorkerDefinitionColumn(Name alias, Table<WorkerDefinitionColumnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> WorkerDefinitionColumn(Table<O> child, ForeignKey<O, WorkerDefinitionColumnRecord> key) {
        super(child, key, WORKER_DEFINITION_COLUMN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.WORKER_DEFINITION_COLUMN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WorkerDefinitionColumnRecord> getPrimaryKey() {
        return Keys.WORKER_DEFINITION_COLUMN_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WorkerDefinitionColumnRecord>> getKeys() {
        return Arrays.<UniqueKey<WorkerDefinitionColumnRecord>>asList(Keys.WORKER_DEFINITION_COLUMN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WorkerDefinitionColumnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WorkerDefinitionColumnRecord, ?>>asList(Keys.WORKER_DEFINITION_COLUMN__FK_WORKER_DEFINITION_INPUT_COLUMN_WORKER_DEFINITION_ID);
    }

    public WorkerDefinition workerDefinition() {
        return new WorkerDefinition(this, Keys.WORKER_DEFINITION_COLUMN__FK_WORKER_DEFINITION_INPUT_COLUMN_WORKER_DEFINITION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerDefinitionColumn as(String alias) {
        return new WorkerDefinitionColumn(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerDefinitionColumn as(Name alias) {
        return new WorkerDefinitionColumn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkerDefinitionColumn rename(String name) {
        return new WorkerDefinitionColumn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorkerDefinitionColumn rename(Name name) {
        return new WorkerDefinitionColumn(name, null);
    }
}
