/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.Column;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ColumnRecord extends UpdatableRecordImpl<ColumnRecord> implements Record7<Long, String, String, String, Boolean, Long, Integer> {

    private static final long serialVersionUID = -326927688;

    /**
     * Setter for <code>column.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>column.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>column.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>column.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>column.class</code>.
     */
    public void setClass_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>column.class</code>.
     */
    public String getClass_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>column.format</code>.
     */
    public void setFormat(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>column.format</code>.
     */
    public String getFormat() {
        return (String) get(3);
    }

    /**
     * Setter for <code>column.nullable</code>.
     */
    public void setNullable(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>column.nullable</code>.
     */
    public Boolean getNullable() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>column.data_series_id</code>.
     */
    public void setDataSeriesId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>column.data_series_id</code>.
     */
    public Long getDataSeriesId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>column.index</code>.
     */
    public void setIndex(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>column.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Boolean, Long, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, Boolean, Long, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Column.COLUMN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Column.COLUMN.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Column.COLUMN.CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Column.COLUMN.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Column.COLUMN.NULLABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Column.COLUMN.DATA_SERIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Column.COLUMN.INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getNullable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getDataSeriesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getNullable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDataSeriesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value3(String value) {
        setClass_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value4(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value5(Boolean value) {
        setNullable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value6(Long value) {
        setDataSeriesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord value7(Integer value) {
        setIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ColumnRecord values(Long value1, String value2, String value3, String value4, Boolean value5, Long value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ColumnRecord
     */
    public ColumnRecord() {
        super(Column.COLUMN);
    }

    /**
     * Create a detached, initialised ColumnRecord
     */
    public ColumnRecord(Long id, String name, String class_, String format, Boolean nullable, Long dataSeriesId, Integer index) {
        super(Column.COLUMN);

        set(0, id);
        set(1, name);
        set(2, class_);
        set(3, format);
        set(4, nullable);
        set(5, dataSeriesId);
        set(6, index);
    }
}
