/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.ExternalClient;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalClientRecord extends UpdatableRecordImpl<ExternalClientRecord> implements Record7<Long, String, String, Long, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>external_client.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>external_client.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>external_client.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>external_client.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>external_client.token</code>.
     */
    public void setToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>external_client.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>external_client.task_id</code>.
     */
    public void setTaskId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>external_client.task_id</code>.
     */
    public Long getTaskId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>external_client.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>external_client.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>external_client.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>external_client.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>external_client.user_id</code>.
     */
    public void setUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>external_client.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Long, LocalDateTime, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, String, Long, LocalDateTime, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ExternalClient.EXTERNAL_CLIENT.ID;
    }

    @Override
    public Field<String> field2() {
        return ExternalClient.EXTERNAL_CLIENT.NAME;
    }

    @Override
    public Field<String> field3() {
        return ExternalClient.EXTERNAL_CLIENT.TOKEN;
    }

    @Override
    public Field<Long> field4() {
        return ExternalClient.EXTERNAL_CLIENT.TASK_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ExternalClient.EXTERNAL_CLIENT.DELETED_AT;
    }

    @Override
    public Field<String> field6() {
        return ExternalClient.EXTERNAL_CLIENT.DESCRIPTION;
    }

    @Override
    public Field<Long> field7() {
        return ExternalClient.EXTERNAL_CLIENT.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getToken();
    }

    @Override
    public Long component4() {
        return getTaskId();
    }

    @Override
    public LocalDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public Long component7() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getToken();
    }

    @Override
    public Long value4() {
        return getTaskId();
    }

    @Override
    public LocalDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public Long value7() {
        return getUserId();
    }

    @Override
    public ExternalClientRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ExternalClientRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ExternalClientRecord value3(String value) {
        setToken(value);
        return this;
    }

    @Override
    public ExternalClientRecord value4(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public ExternalClientRecord value5(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public ExternalClientRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ExternalClientRecord value7(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ExternalClientRecord values(Long value1, String value2, String value3, Long value4, LocalDateTime value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExternalClientRecord
     */
    public ExternalClientRecord() {
        super(ExternalClient.EXTERNAL_CLIENT);
    }

    /**
     * Create a detached, initialised ExternalClientRecord
     */
    public ExternalClientRecord(Long id, String name, String token, Long taskId, LocalDateTime deletedAt, String description, Long userId) {
        super(ExternalClient.EXTERNAL_CLIENT);

        setId(id);
        setName(name);
        setToken(token);
        setTaskId(taskId);
        setDeletedAt(deletedAt);
        setDescription(description);
        setUserId(userId);
    }
}
