/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.InvocationParameter;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvocationParameterRecord extends UpdatableRecordImpl<InvocationParameterRecord> implements Record4<Long, String, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>invocation_parameter.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>invocation_parameter.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>invocation_parameter.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>invocation_parameter.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>invocation_parameter.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>invocation_parameter.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>invocation_parameter.invocation_id</code>.
     */
    public void setInvocationId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>invocation_parameter.invocation_id</code>.
     */
    public Long getInvocationId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InvocationParameter.INVOCATION_PARAMETER.ID;
    }

    @Override
    public Field<String> field2() {
        return InvocationParameter.INVOCATION_PARAMETER.NAME;
    }

    @Override
    public Field<String> field3() {
        return InvocationParameter.INVOCATION_PARAMETER.VALUE;
    }

    @Override
    public Field<Long> field4() {
        return InvocationParameter.INVOCATION_PARAMETER.INVOCATION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public Long component4() {
        return getInvocationId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public Long value4() {
        return getInvocationId();
    }

    @Override
    public InvocationParameterRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InvocationParameterRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public InvocationParameterRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public InvocationParameterRecord value4(Long value) {
        setInvocationId(value);
        return this;
    }

    @Override
    public InvocationParameterRecord values(Long value1, String value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvocationParameterRecord
     */
    public InvocationParameterRecord() {
        super(InvocationParameter.INVOCATION_PARAMETER);
    }

    /**
     * Create a detached, initialised InvocationParameterRecord
     */
    public InvocationParameterRecord(Long id, String name, String value, Long invocationId) {
        super(InvocationParameter.INVOCATION_PARAMETER);

        setId(id);
        setName(name);
        setValue(value);
        setInvocationId(invocationId);
    }
}
