/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.SeriesTable;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeriesTableRecord extends UpdatableRecordImpl<SeriesTableRecord> implements Record4<Long, String, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>series_table.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>series_table.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>series_table.table_name</code>.
     */
    public void setTableName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>series_table.table_name</code>.
     */
    public String getTableName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>series_table.data_series_id</code>.
     */
    public void setDataSeriesId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>series_table.data_series_id</code>.
     */
    public Long getDataSeriesId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>series_table.delete_at</code>.
     */
    public void setDeleteAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>series_table.delete_at</code>.
     */
    public LocalDateTime getDeleteAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, Long, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, Long, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SeriesTable.SERIES_TABLE.ID;
    }

    @Override
    public Field<String> field2() {
        return SeriesTable.SERIES_TABLE.TABLE_NAME;
    }

    @Override
    public Field<Long> field3() {
        return SeriesTable.SERIES_TABLE.DATA_SERIES_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return SeriesTable.SERIES_TABLE.DELETE_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTableName();
    }

    @Override
    public Long component3() {
        return getDataSeriesId();
    }

    @Override
    public LocalDateTime component4() {
        return getDeleteAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTableName();
    }

    @Override
    public Long value3() {
        return getDataSeriesId();
    }

    @Override
    public LocalDateTime value4() {
        return getDeleteAt();
    }

    @Override
    public SeriesTableRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SeriesTableRecord value2(String value) {
        setTableName(value);
        return this;
    }

    @Override
    public SeriesTableRecord value3(Long value) {
        setDataSeriesId(value);
        return this;
    }

    @Override
    public SeriesTableRecord value4(LocalDateTime value) {
        setDeleteAt(value);
        return this;
    }

    @Override
    public SeriesTableRecord values(Long value1, String value2, Long value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SeriesTableRecord
     */
    public SeriesTableRecord() {
        super(SeriesTable.SERIES_TABLE);
    }

    /**
     * Create a detached, initialised SeriesTableRecord
     */
    public SeriesTableRecord(Long id, String tableName, Long dataSeriesId, LocalDateTime deleteAt) {
        super(SeriesTable.SERIES_TABLE);

        setId(id);
        setTableName(tableName);
        setDataSeriesId(dataSeriesId);
        setDeleteAt(deleteAt);
    }
}
