/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.TagDataconnection;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagDataconnectionRecord extends UpdatableRecordImpl<TagDataconnectionRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tag_dataconnection.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tag_dataconnection.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tag_dataconnection.dataconnection_id</code>.
     */
    public void setDataconnectionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>tag_dataconnection.dataconnection_id</code>.
     */
    public Long getDataconnectionId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TagDataconnection.TAG_DATACONNECTION.TAG_ID;
    }

    @Override
    public Field<Long> field2() {
        return TagDataconnection.TAG_DATACONNECTION.DATACONNECTION_ID;
    }

    @Override
    public Long component1() {
        return getTagId();
    }

    @Override
    public Long component2() {
        return getDataconnectionId();
    }

    @Override
    public Long value1() {
        return getTagId();
    }

    @Override
    public Long value2() {
        return getDataconnectionId();
    }

    @Override
    public TagDataconnectionRecord value1(Long value) {
        setTagId(value);
        return this;
    }

    @Override
    public TagDataconnectionRecord value2(Long value) {
        setDataconnectionId(value);
        return this;
    }

    @Override
    public TagDataconnectionRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagDataconnectionRecord
     */
    public TagDataconnectionRecord() {
        super(TagDataconnection.TAG_DATACONNECTION);
    }

    /**
     * Create a detached, initialised TagDataconnectionRecord
     */
    public TagDataconnectionRecord(Long tagId, Long dataconnectionId) {
        super(TagDataconnection.TAG_DATACONNECTION);

        setTagId(tagId);
        setDataconnectionId(dataconnectionId);
    }
}
