/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.Task;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends UpdatableRecordImpl<TaskRecord> implements Record7<Long, String, Long, String, Long, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>task.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>task.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>task.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>task.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>task.worker_def_id</code>.
     */
    public void setWorkerDefId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>task.worker_def_id</code>.
     */
    public Long getWorkerDefId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>task.cron_trigger</code>.
     */
    public void setCronTrigger(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>task.cron_trigger</code>.
     */
    public String getCronTrigger() {
        return (String) get(3);
    }

    /**
     * Setter for <code>task.task_trigger</code>.
     */
    public void setTaskTrigger(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>task.task_trigger</code>.
     */
    public Long getTaskTrigger() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>task.task_type</code>.
     */
    public void setTaskType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>task.task_type</code>.
     */
    public String getTaskType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>task.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>task.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, Long, String, Long, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, Long, String, Long, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Task.TASK.ID;
    }

    @Override
    public Field<String> field2() {
        return Task.TASK.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Task.TASK.WORKER_DEF_ID;
    }

    @Override
    public Field<String> field4() {
        return Task.TASK.CRON_TRIGGER;
    }

    @Override
    public Field<Long> field5() {
        return Task.TASK.TASK_TRIGGER;
    }

    @Override
    public Field<String> field6() {
        return Task.TASK.TASK_TYPE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Task.TASK.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getWorkerDefId();
    }

    @Override
    public String component4() {
        return getCronTrigger();
    }

    @Override
    public Long component5() {
        return getTaskTrigger();
    }

    @Override
    public String component6() {
        return getTaskType();
    }

    @Override
    public LocalDateTime component7() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getWorkerDefId();
    }

    @Override
    public String value4() {
        return getCronTrigger();
    }

    @Override
    public Long value5() {
        return getTaskTrigger();
    }

    @Override
    public String value6() {
        return getTaskType();
    }

    @Override
    public LocalDateTime value7() {
        return getDeletedAt();
    }

    @Override
    public TaskRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TaskRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TaskRecord value3(Long value) {
        setWorkerDefId(value);
        return this;
    }

    @Override
    public TaskRecord value4(String value) {
        setCronTrigger(value);
        return this;
    }

    @Override
    public TaskRecord value5(Long value) {
        setTaskTrigger(value);
        return this;
    }

    @Override
    public TaskRecord value6(String value) {
        setTaskType(value);
        return this;
    }

    @Override
    public TaskRecord value7(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public TaskRecord values(Long value1, String value2, Long value3, String value4, Long value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskRecord
     */
    public TaskRecord() {
        super(Task.TASK);
    }

    /**
     * Create a detached, initialised TaskRecord
     */
    public TaskRecord(Long id, String name, Long workerDefId, String cronTrigger, Long taskTrigger, String taskType, LocalDateTime deletedAt) {
        super(Task.TASK);

        setId(id);
        setName(name);
        setWorkerDefId(workerDefId);
        setCronTrigger(cronTrigger);
        setTaskTrigger(taskTrigger);
        setTaskType(taskType);
        setDeletedAt(deletedAt);
    }
}
