/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.TaskOutputColumn;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskOutputColumnRecord extends UpdatableRecordImpl<TaskOutputColumnRecord> implements Record8<Long, Integer, String, String, String, String, Boolean, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>task_output_column.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>task_output_column.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>task_output_column.index</code>.
     */
    public void setIndex(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>task_output_column.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>task_output_column.alias</code>.
     */
    public void setAlias(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>task_output_column.alias</code>.
     */
    public String getAlias() {
        return (String) get(2);
    }

    /**
     * Setter for <code>task_output_column.column_name</code>.
     */
    public void setColumnName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>task_output_column.column_name</code>.
     */
    public String getColumnName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>task_output_column.class</code>.
     */
    public void setClass_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>task_output_column.class</code>.
     */
    public String getClass_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>task_output_column.format</code>.
     */
    public void setFormat(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>task_output_column.format</code>.
     */
    public String getFormat() {
        return (String) get(5);
    }

    /**
     * Setter for <code>task_output_column.nullable</code>.
     */
    public void setNullable(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>task_output_column.nullable</code>.
     */
    public Boolean getNullable() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>task_output_column.task_id</code>.
     */
    public void setTaskId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>task_output_column.task_id</code>.
     */
    public Long getTaskId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Integer, String, String, String, String, Boolean, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Integer, String, String, String, String, Boolean, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.INDEX;
    }

    @Override
    public Field<String> field3() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.ALIAS;
    }

    @Override
    public Field<String> field4() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.COLUMN_NAME;
    }

    @Override
    public Field<String> field5() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.CLASS;
    }

    @Override
    public Field<String> field6() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.FORMAT;
    }

    @Override
    public Field<Boolean> field7() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.NULLABLE;
    }

    @Override
    public Field<Long> field8() {
        return TaskOutputColumn.TASK_OUTPUT_COLUMN.TASK_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getIndex();
    }

    @Override
    public String component3() {
        return getAlias();
    }

    @Override
    public String component4() {
        return getColumnName();
    }

    @Override
    public String component5() {
        return getClass_();
    }

    @Override
    public String component6() {
        return getFormat();
    }

    @Override
    public Boolean component7() {
        return getNullable();
    }

    @Override
    public Long component8() {
        return getTaskId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getIndex();
    }

    @Override
    public String value3() {
        return getAlias();
    }

    @Override
    public String value4() {
        return getColumnName();
    }

    @Override
    public String value5() {
        return getClass_();
    }

    @Override
    public String value6() {
        return getFormat();
    }

    @Override
    public Boolean value7() {
        return getNullable();
    }

    @Override
    public Long value8() {
        return getTaskId();
    }

    @Override
    public TaskOutputColumnRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value2(Integer value) {
        setIndex(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value3(String value) {
        setAlias(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value4(String value) {
        setColumnName(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value5(String value) {
        setClass_(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value6(String value) {
        setFormat(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value7(Boolean value) {
        setNullable(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord value8(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public TaskOutputColumnRecord values(Long value1, Integer value2, String value3, String value4, String value5, String value6, Boolean value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaskOutputColumnRecord
     */
    public TaskOutputColumnRecord() {
        super(TaskOutputColumn.TASK_OUTPUT_COLUMN);
    }

    /**
     * Create a detached, initialised TaskOutputColumnRecord
     */
    public TaskOutputColumnRecord(Long id, Integer index, String alias, String columnName, String class_, String format, Boolean nullable, Long taskId) {
        super(TaskOutputColumn.TASK_OUTPUT_COLUMN);

        setId(id);
        setIndex(index);
        setAlias(alias);
        setColumnName(columnName);
        setClass_(class_);
        setFormat(format);
        setNullable(nullable);
        setTaskId(taskId);
    }
}
