/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.Worker;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerRecord extends UpdatableRecordImpl<WorkerRecord> implements Record6<Long, String, Timestamp, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = 2039712910;

    /**
     * Setter for <code>worker.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>worker.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>worker.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>worker.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>worker.accepted_on</code>.
     */
    public void setAcceptedOn(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>worker.accepted_on</code>.
     */
    public Timestamp getAcceptedOn() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>worker.last_seen</code>.
     */
    public void setLastSeen(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>worker.last_seen</code>.
     */
    public Timestamp getLastSeen() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>worker.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>worker.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>worker.definition_id</code>.
     */
    public void setDefinitionId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>worker.definition_id</code>.
     */
    public Long getDefinitionId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Timestamp, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, Timestamp, Timestamp, Timestamp, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Worker.WORKER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Worker.WORKER.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Worker.WORKER.ACCEPTED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Worker.WORKER.LAST_SEEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Worker.WORKER.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Worker.WORKER.DEFINITION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getAcceptedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getLastSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getDefinitionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getAcceptedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastSeen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDefinitionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value3(Timestamp value) {
        setAcceptedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value4(Timestamp value) {
        setLastSeen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value5(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord value6(Long value) {
        setDefinitionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorkerRecord values(Long value1, String value2, Timestamp value3, Timestamp value4, Timestamp value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerRecord
     */
    public WorkerRecord() {
        super(Worker.WORKER);
    }

    /**
     * Create a detached, initialised WorkerRecord
     */
    public WorkerRecord(Long id, String token, Timestamp acceptedOn, Timestamp lastSeen, Timestamp deletedAt, Long definitionId) {
        super(Worker.WORKER);

        set(0, id);
        set(1, token);
        set(2, acceptedOn);
        set(3, lastSeen);
        set(4, deletedAt);
        set(5, definitionId);
    }
}
