/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.Worker;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerRecord extends UpdatableRecordImpl<WorkerRecord> implements Record6<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>worker.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>worker.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>worker.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>worker.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>worker.accepted_on</code>.
     */
    public void setAcceptedOn(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>worker.accepted_on</code>.
     */
    public LocalDateTime getAcceptedOn() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>worker.last_seen</code>.
     */
    public void setLastSeen(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>worker.last_seen</code>.
     */
    public LocalDateTime getLastSeen() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>worker.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>worker.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>worker.definition_id</code>.
     */
    public void setDefinitionId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>worker.definition_id</code>.
     */
    public Long getDefinitionId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, LocalDateTime, LocalDateTime, LocalDateTime, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Worker.WORKER.ID;
    }

    @Override
    public Field<String> field2() {
        return Worker.WORKER.TOKEN;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Worker.WORKER.ACCEPTED_ON;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Worker.WORKER.LAST_SEEN;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Worker.WORKER.DELETED_AT;
    }

    @Override
    public Field<Long> field6() {
        return Worker.WORKER.DEFINITION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getToken();
    }

    @Override
    public LocalDateTime component3() {
        return getAcceptedOn();
    }

    @Override
    public LocalDateTime component4() {
        return getLastSeen();
    }

    @Override
    public LocalDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public Long component6() {
        return getDefinitionId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getToken();
    }

    @Override
    public LocalDateTime value3() {
        return getAcceptedOn();
    }

    @Override
    public LocalDateTime value4() {
        return getLastSeen();
    }

    @Override
    public LocalDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public Long value6() {
        return getDefinitionId();
    }

    @Override
    public WorkerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkerRecord value2(String value) {
        setToken(value);
        return this;
    }

    @Override
    public WorkerRecord value3(LocalDateTime value) {
        setAcceptedOn(value);
        return this;
    }

    @Override
    public WorkerRecord value4(LocalDateTime value) {
        setLastSeen(value);
        return this;
    }

    @Override
    public WorkerRecord value5(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public WorkerRecord value6(Long value) {
        setDefinitionId(value);
        return this;
    }

    @Override
    public WorkerRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4, LocalDateTime value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerRecord
     */
    public WorkerRecord() {
        super(Worker.WORKER);
    }

    /**
     * Create a detached, initialised WorkerRecord
     */
    public WorkerRecord(Long id, String token, LocalDateTime acceptedOn, LocalDateTime lastSeen, LocalDateTime deletedAt, Long definitionId) {
        super(Worker.WORKER);

        setId(id);
        setToken(token);
        setAcceptedOn(acceptedOn);
        setLastSeen(lastSeen);
        setDeletedAt(deletedAt);
        setDefinitionId(definitionId);
    }
}
