/*
 * This file is generated by jOOQ.
 */
package fi.jubic.quanta.db.tables.records;


import fi.jubic.quanta.db.tables.WorkerDefinition;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkerDefinitionRecord extends UpdatableRecordImpl<WorkerDefinitionRecord> implements Record5<Long, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>worker_definition.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>worker_definition.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>worker_definition.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>worker_definition.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>worker_definition.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>worker_definition.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>worker_definition.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>worker_definition.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>worker_definition.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>worker_definition.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WorkerDefinition.WORKER_DEFINITION.ID;
    }

    @Override
    public Field<String> field2() {
        return WorkerDefinition.WORKER_DEFINITION.TYPE;
    }

    @Override
    public Field<String> field3() {
        return WorkerDefinition.WORKER_DEFINITION.NAME;
    }

    @Override
    public Field<String> field4() {
        return WorkerDefinition.WORKER_DEFINITION.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return WorkerDefinition.WORKER_DEFINITION.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public WorkerDefinitionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WorkerDefinitionRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public WorkerDefinitionRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public WorkerDefinitionRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public WorkerDefinitionRecord value5(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public WorkerDefinitionRecord values(Long value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkerDefinitionRecord
     */
    public WorkerDefinitionRecord() {
        super(WorkerDefinition.WORKER_DEFINITION);
    }

    /**
     * Create a detached, initialised WorkerDefinitionRecord
     */
    public WorkerDefinitionRecord(Long id, String type, String name, String description, LocalDateTime deletedAt) {
        super(WorkerDefinition.WORKER_DEFINITION);

        setId(id);
        setType(type);
        setName(name);
        setDescription(description);
        setDeletedAt(deletedAt);
    }
}
